### PR TITLE
Add option to use gcloud for getting user auth

### PR DESCRIPTION
**Pull request by thrykol**

### CODE REVIEW

**Review by hrvolapeter — APPROVED** [review]
LGTM

I would maybe wait for #30 to be merged which contains some checks through githubactions

closes #27

**Comment by hrvolapeter** [comment]
@thrykol could you fix the conflict with master? I would do it but the changes are in your fork.

**Comment by djc** [comment]
Would be nice to rebase this rather than merge it. Hopefully it's not too much of a pain!

**Comment by thrykol** [comment]
@hrvolapeter conflicts have been resolved in the fork.  Once this gets merged, what's the process for rolling a new release?

**Comment by hrvolapeter** [comment]
Hi @thrykol, thanks for the conflicts, I'll first do some checks on the current master and I'll push new version to cargo hopefully today

**Pull request merged**
